name: Test
on: [push]
jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.14', '1.13' ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -v -timeout 15m ./...
        env:
          CGO_ENABLED: 0
