name: Test
on: [push]
jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.14', '1.13' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}

      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Build
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
          go env
          go build -i -v .

      - name: Test
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
          go env
          go test -v -short .
