name: Test
on: [push]
jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.14', '1.13' ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -i -v .

      - name: Test
        run: go test -v -p 1 ./...

      - name: Test
        run: go test -v -race -test.run="TestSimulate_(100op|1000op)"
