name: Test
on: [push]
jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go: [ '1.14', '1.13' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - uses: actions/checkout@v1

      - name: Build
        run: go build -i -v .

      - name: Test
        run: go test -v -short .
